[project]
name = "models"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "transformers>=4.48.1",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
# Tell Hatchling to include the models package from the src/ directory
include = ["packages/models"]


[tool.uv]
# manage the environment like a package rather than a standalone virtual environment
package = true